"""unique usernames

Revision ID: e93c042b7b60
Revises: 6f7ab8dc3ee3
Create Date: 2023-12-08 19:17:30.338466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e93c042b7b60"
down_revision = "6f7ab8dc3ee3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ["username"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="unique")

    # ### end Alembic commands ###
